[2017-08-14 14:52:16,804] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for d26134dd-3f68-4efb-9a29-a293368934a2 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Cannot open database "DAL_SEC" requested by the login. The login failed.
Login failed for user 'CD17D-6165-SYW\Administrator'.
   at BL.TaskProcessService.OperationProvider.RunSP(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-14 14:52:52,386] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 059d9b15-68d0-4392-9f63-8f6c8b391144 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Invalid object name 'Job_2_20160701_133.tblFactLoanCustomer'.
   at BL.TaskProcessService.OperationProvider.RunSP(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-14 14:53:06,940] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 298efc8d-0a09-4d57-b6bd-98911e166fb7 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Invalid object name 'Job_2_20160701_133.tblFactLoanCustomer'.
   at BL.TaskProcessService.OperationProvider.RunSP(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-14 14:56:04,474] ERROR Securitisation.Utilities.Common.Log4NetLogService - Create session failed
System.IO.FileNotFoundException: Could not find file 'E:\TSSWCFServices\AppData\TaskProcessEngine\Task\'.
File name: 'E:\TSSWCFServices\AppData\TaskProcessEngine\Task\'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   at TaskProcessEngine.SessionManagementService.CreateSessionByTaskCode(String applicationDomain, String sessionVariable, String taskCode) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\SessionManagementService.svc.cs:line 120
[2017-08-14 14:58:08,188] ERROR Securitisation.Utilities.Common.Log4NetLogService - Create session failed
System.IO.FileNotFoundException: Could not find file 'E:\TSSWCFServices\AppData\TaskProcessEngine\Task\'.
File name: 'E:\TSSWCFServices\AppData\TaskProcessEngine\Task\'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   at TaskProcessEngine.SessionManagementService.CreateSessionByTaskCode(String applicationDomain, String sessionVariable, String taskCode) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\SessionManagementService.svc.cs:line 120
[2017-08-14 15:00:15,522] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for eab9b884-6ee4-4acc-9604-4228705b3701 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Invalid object name 'Job_2_20160701_133.tblFactLoanCustomer'.
   at BL.TaskProcessService.OperationProvider.RunSP(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-14 15:00:27,953] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for eab9b884-6ee4-4acc-9604-4228705b3701 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Invalid object name 'Job_2_20160701_133.tblFactLoanCustomer'.
   at BL.TaskProcessService.OperationProvider.RunSP(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-14 15:01:05,807] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for eab9b884-6ee4-4acc-9604-4228705b3701 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Invalid object name 'Job_2_20160701_133.tblFactLoanCustomer'.
   at BL.TaskProcessService.OperationProvider.RunSP(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
