[2017-08-17 17:25:36,350] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 2378f07c-bb1c-454d-9cf8-54081d95c8e2 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'e:\temp\CashflowCalculationLog_0.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path)
   at AddIn.CashflowScript.GenericBondWaterfallPlus.ApplyAllocationPIIndividualAccount_V2(BondFeeContext bondFeeContext, Int32 iCurrentPosition, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   at AddIn.CashflowScript.GenericBondWaterfallPlus.RunWaterfall_IncomePlus_V2(Int32 iCurrentPosition, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   at EquationProvider.CashFlowEquationProvider.ExecuteAllInLoop(Int32 CurrentPosition, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   at EquationProvider.CashFlowEquationProvider.ExecuteAll(Int32 startPosition, Int32 endPosition, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 17:25:57,819] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 2378f07c-bb1c-454d-9cf8-54081d95c8e2 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EquationProvider.CashFlowEquationProvider.EC_TrustPlanAccount_AssetPoolBalance(Int32 iCurrentPosition, String sCashFlowName, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   at EquationProvider.CashFlowEquationProvider.ExecuteAllInLoop(Int32 CurrentPosition, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   at EquationProvider.CashFlowEquationProvider.ExecuteAll(Int32 startPosition, Int32 endPosition, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 17:26:56,754] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for ac61acdf-9b3a-45d5-a9f3-0ae0d0b8a064 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'e:\temp\CashflowCalculationLog_0.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path)
   at AddIn.CashflowScript.GenericBondWaterfallPlus.ApplyAllocationPIIndividualAccount_V2(BondFeeContext bondFeeContext, Int32 iCurrentPosition, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   at AddIn.CashflowScript.GenericBondWaterfallPlus.RunWaterfall_IncomePlus_V2(Int32 iCurrentPosition, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   at EquationProvider.CashFlowEquationProvider.ExecuteAllInLoop(Int32 CurrentPosition, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   at EquationProvider.CashFlowEquationProvider.ExecuteAll(Int32 startPosition, Int32 endPosition, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 17:28:38,534] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for ac61acdf-9b3a-45d5-a9f3-0ae0d0b8a064 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EquationProvider.CashFlowEquationProvider.EC_TrustPlanAccount_AssetPoolBalance(Int32 iCurrentPosition, String sCashFlowName, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   at EquationProvider.CashFlowEquationProvider.ExecuteAllInLoop(Int32 CurrentPosition, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   at EquationProvider.CashFlowEquationProvider.ExecuteAll(Int32 startPosition, Int32 endPosition, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 17:29:55,006] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for ac61acdf-9b3a-45d5-a9f3-0ae0d0b8a064 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EquationProvider.CashFlowEquationProvider.EC_TrustPlanAccount_AssetPoolBalance(Int32 iCurrentPosition, String sCashFlowName, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   at EquationProvider.CashFlowEquationProvider.ExecuteAllInLoop(Int32 CurrentPosition, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   at EquationProvider.CashFlowEquationProvider.ExecuteAll(Int32 startPosition, Int32 endPosition, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 17:40:51,814] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for d593ef08-2e16-489d-af2a-0d2542e4e0c9 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: Can not find [DefaultCurve] from Session Context Array.
The given key was not present in the dictionary.
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.InitSessionContextArrayFromMemory(String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 17:45:25,130] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 75116be7-761e-4595-85e0-356729548c59 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: Can not find [DefaultCurve] from Session Context Array.
The given key was not present in the dictionary.
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.InitSessionContextArrayFromMemory(String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 17:47:34,131] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 827372e1-2432-4146-a9a6-172bda9aae1b failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: Can not find [DefaultCurve] from Session Context Array.
The given key was not present in the dictionary.
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.InitSessionContextArrayFromMemory(String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 17:48:20,935] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 827372e1-2432-4146-a9a6-172bda9aae1b failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.InitSessionContextArrayFromMemory(String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 17:53:46,547] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 827372e1-2432-4146-a9a6-172bda9aae1b failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.InitSessionContextArrayFromMemory(String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 17:56:52,415] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for af1f9b60-2330-4799-ba7c-1d43d680ee15 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: Can not find [DefaultCurve] from Session Context Array.
The given key was not present in the dictionary.
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.InitSessionContextArrayFromMemory(String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 17:57:20,860] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for af1f9b60-2330-4799-ba7c-1d43d680ee15 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 17:57:50,930] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for af1f9b60-2330-4799-ba7c-1d43d680ee15 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EquationProvider.CashFlowEquationProvider.EC_TrustPlanAccount_AssetPoolBalance(Int32 iCurrentPosition, String sCashFlowName, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   at EquationProvider.CashFlowEquationProvider.ExecuteAllInLoop(Int32 CurrentPosition, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   at EquationProvider.CashFlowEquationProvider.ExecuteAll(Int32 startPosition, Int32 endPosition, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 17:59:13,213] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 580a32f4-879c-4b7d-8ab1-58abf422ed8b failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: Can not find [DefaultCurve] from Session Context Array.
The given key was not present in the dictionary.
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.InitSessionContextArrayFromMemory(String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 18:35:41,511] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 04d4e550-38fa-4875-92a1-91ed6941bb88 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: Can not find [DefaultCurve] from Session Context Array.
The given key was not present in the dictionary.
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.InitSessionContextArrayFromMemory(String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
