[2017-08-17 20:50:09,590] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 5efe208c-c137-4b0d-a049-fa461d4157f4 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: Can not find [DefaultCurve] from Session Context Array.
The given key was not present in the dictionary.
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.InitSessionContextArrayFromMemory(String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 20:56:27,770] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 5de6247b-1370-477b-a97e-cb274996f47f failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: Can not find [DefaultCurve] from Session Context Array.
The given key was not present in the dictionary.
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.InitSessionContextArrayFromMemory(String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 21:01:51,794] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for d68d43df-76b3-4447-9ba6-f4342891822a failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.ReadTaskArrayFromDataBase(String sCashflowName, String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 21:04:38,702] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for d8c6adfd-870c-457a-9e12-67f1ea575899 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.ReadTaskArrayFromDataBase(String sCashflowName, String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 21:05:40,698] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 1e7a2465-cc6c-4cd7-a6ec-c1b16a8d6fe1 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.ReadTaskArrayFromDataBase(String sCashflowName, String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 21:06:48,037] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 295cb669-3c31-4080-ac16-3dfe80b55812 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not find file 'C:\Temp\AddIn.CashflowScript.dll'.
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 21:13:32,655] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 6edb2498-fca4-4408-b5f5-57e64946085f failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: Can not find [DefaultCurve] from Session Context Array.
The given key was not present in the dictionary.
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.InitSessionContextArrayFromMemory(String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 21:17:27,024] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for f084683e-2875-4075-bd61-38757e9f59d3 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: Can not find [DefaultCurve] from Session Context Array.
The given key was not present in the dictionary.
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.InitSessionContextArrayFromMemory(String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 21:25:07,654] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for f3d87bbe-0f2c-4201-a171-7aa186f8f3c4 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: Can not find [DefaultCurve] from Session Context Array.
The given key was not present in the dictionary.
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.InitSessionContextArrayFromMemory(String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 21:30:56,070] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 529797e9-1073-4074-83e5-ba1c3bbf3443 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: Can not find [DefaultCurve] from Session Context Array.
The given key was not present in the dictionary.
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.InitSessionContextArrayFromMemory(String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 21:51:24,897] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 34e7368c-23b0-4b15-a1b9-c0c23297604e failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.ReadTaskArrayFromDataBase(String sCashflowName, String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 21:53:08,273] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for d0aa8b97-b8c8-435e-8606-7a9d9e2ac0a1 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: Can not find [DefaultCurve] from Session Context Array.
The given key was not present in the dictionary.
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.InitSessionContextArrayFromMemory(String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 21:55:45,085] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 66f017bf-7aec-4d4b-b64d-8677029f8482 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: Can not find [DefaultCurve] from Session Context Array.
The given key was not present in the dictionary.
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.InitSessionContextArrayFromMemory(String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 22:04:10,746] ERROR Securitisation.Utilities.Common.Log4NetLogService - Create session failed
System.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'ProcessActionCodeId', table 'TaskProcess.Task.SessionProcessStatus'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Securitisation.Utilities.SQL.UtilSqlRunQueryADONET.RunNonQueryADONETByQueryString(String sQueryString, List`1 glParameters, String sConnectionString)
   at DADP.TaskEntity.ProcessTaskHelper.CreateSessionProcessStatus(Guid SessionId, String XmlTask)
   at TaskProcessEngine.SessionManagementService.CreateSessionByTaskCode(String applicationDomain, String sessionVariable, String taskCode) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\SessionManagementService.svc.cs:line 125
ClientConnectionId:bba795fc-34bb-4526-b5b5-9656eef6d461
Error Number:515,State:2,Class:16
[2017-08-17 22:04:14,337] ERROR Securitisation.Utilities.Common.Log4NetLogService - Create session failed
System.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'ProcessActionCodeId', table 'TaskProcess.Task.SessionProcessStatus'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Securitisation.Utilities.SQL.UtilSqlRunQueryADONET.RunNonQueryADONETByQueryString(String sQueryString, List`1 glParameters, String sConnectionString)
   at DADP.TaskEntity.ProcessTaskHelper.CreateSessionProcessStatus(Guid SessionId, String XmlTask)
   at TaskProcessEngine.SessionManagementService.CreateSessionByTaskCode(String applicationDomain, String sessionVariable, String taskCode) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\SessionManagementService.svc.cs:line 125
ClientConnectionId:bba795fc-34bb-4526-b5b5-9656eef6d461
Error Number:515,State:2,Class:16
[2017-08-17 22:04:32,564] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 516b1567-933a-4d77-a2fd-5a1567b7d433 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.ReadTaskArrayFromDataBase(String sCashflowName, String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 22:21:18,740] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 78e151d0-82a5-466c-9600-994fd718ea72 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.ReadTaskArrayFromDataBase(String sCashflowName, String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 22:22:55,114] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for ae4ce6e3-0b19-4f74-beef-31a49baffd77 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: Can not find [DefaultCurve] from Session Context Array.
The given key was not present in the dictionary.
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.InitSessionContextArrayFromMemory(String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
[2017-08-17 22:24:05,326] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 8ec3d738-975d-4441-bccf-11d7566dadd8 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: Can not find [DefaultCurve] from Session Context Array.
The given key was not present in the dictionary.
   at DADP.CashFlowStudioEntity.CashFlowInputProvider.InitSessionContextArrayFromMemory(String sSessionId, String sConnectionString, String sAppDomain, Dictionary`2& sessionContext, Dictionary`2& sessionContextArray)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.CashFlowProvider.RunManagedMethodByPath(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.CashflowService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\CashflowService.svc.cs:line 64
